package com.demo.entities;
// Generated Aug 29, 2021, 4:25:35 PM by Hibernate Tools 5.4.30.Final

import java.math.BigDecimal;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Account generated by hbm2java
 */
@Entity
@Table(name = "account", catalog = "testhibernate")
public class Account implements java.io.Serializable {

	private String accId;
	private String customerName;
	private String email;
	private String phone;
	private BigDecimal balance;

	public Account() {
	}

	public Account(String accId) {
		this.accId = accId;
	}

	public Account(String accId, String customerName, String email, String phone, BigDecimal balance) {
		this.accId = accId;
		this.customerName = customerName;
		this.email = email;
		this.phone = phone;
		this.balance = balance;
	}
	@Id
	public String getAccId() {
		return this.accId;
	}

	public void setAccId(String accId) {
		this.accId = accId;
	}

	public String getCustomerName() {
		return this.customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public BigDecimal getBalance() {
		return this.balance;
	}

	public void setBalance(BigDecimal balance) {
		this.balance = balance;
	}

}
